// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1yN7J6f2rWXtc2uRqoDzUlRkTlQVP3o',
    appId: '1:26214372638:web:bdff59b0c3e9b7f426a50f',
    messagingSenderId: '26214372638',
    projectId: 'authface-40370',
    authDomain: 'authface-40370.firebaseapp.com',
    storageBucket: 'authface-40370.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6wQ4SXHRBrL8xctivKaHDwrPtTvjIqk',
    appId: '1:26214372638:android:5e581ca74cf8694c26a50f',
    messagingSenderId: '26214372638',
    projectId: 'authface-40370',
    storageBucket: 'authface-40370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY5tI-0GY1GEpnQsCF_xcWZnrcio5B3eA',
    appId: '1:26214372638:ios:a35a64332fecb30626a50f',
    messagingSenderId: '26214372638',
    projectId: 'authface-40370',
    storageBucket: 'authface-40370.firebasestorage.app',
    iosBundleId: 'com.example.authface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY5tI-0GY1GEpnQsCF_xcWZnrcio5B3eA',
    appId: '1:26214372638:ios:a35a64332fecb30626a50f',
    messagingSenderId: '26214372638',
    projectId: 'authface-40370',
    storageBucket: 'authface-40370.firebasestorage.app',
    iosBundleId: 'com.example.authface',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk1yN7J6f2rWXtc2uRqoDzUlRkTlQVP3o',
    appId: '1:26214372638:web:b58c36400d5de3f226a50f',
    messagingSenderId: '26214372638',
    projectId: 'authface-40370',
    authDomain: 'authface-40370.firebaseapp.com',
    storageBucket: 'authface-40370.firebasestorage.app',
  );

}